version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
  python_app:
    build: ./python/
    ports:
    - "8899:8899"
    depends_on:
    - prometheus
  golang_app:
    build: ./go/
    depends_on:
    - prometheus
    ports:
    - "7788:7788"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
  node_exporter:
    image: prom/node-exporter:latest
    ports:
    - "9100:9100"
    deploy:
      mode: global
  alertmanager:
    image: prom/alertmanager:latest
    ports:
    - "9093:9093"
    volumes:
    - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
volumes:
  grafana-data: